const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
    console.log('Deleting dummy products generated by the bulk insert script...');

    const result = await prisma.product.deleteMany({
        where: {
            name: {
                contains: '(Bulk ',
            }
        }
    });

    console.log(`Successfully deleted ${result.count} dummy products.`);
}

main()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
